/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.AlumnoData;
import Data.CursadaData;
import Data.MateriaData;
import Modelos.Inscripcion;
import Modelos.Materia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Best smite LAS
 */
public class ConsultasView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private CursadaData cursada;
    private AlumnoData ad;
    private List<Materia> listaMaterias;
    private MateriaData md;

    public ConsultasView(CursadaData inscripcion, AlumnoData alumnoData, MateriaData materias) {
        initComponents();
        modelo = new DefaultTableModel();
        cursada = inscripcion;
        ad = alumnoData;
        md = materias;
        listaMaterias = md.obtenerMaterias();
        llenarCombos();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcmMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDescripcionAlumnos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultas");

        jLabel1.setFont(new java.awt.Font("Gurmukhi MT", 0, 24)); // NOI18N
        jLabel1.setText("ALUMNOS INSCRIPTOS EN MATERIAS ");

        jLabel2.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jLabel2.setText("Materia");

        jcmMaterias.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jcmMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmMateriasActionPerformed(evt);
            }
        });

        jtDescripcionAlumnos = new javax.swing.JTable(){
            public boolean isCellEditable(int RowIndex, int colIndex){
                return false;
            }
        };
        jtDescripcionAlumnos.setFont(new java.awt.Font("Gurmukhi MT", 0, 12)); // NOI18N
        jtDescripcionAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtDescripcionAlumnos.setToolTipText("");
        jScrollPane1.setViewportView(jtDescripcionAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcmMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcmMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmMateriasActionPerformed
        llenarTabla();
    }//GEN-LAST:event_jcmMateriasActionPerformed
    private void llenarCombos() {

        for (Materia m : listaMaterias) {

            jcmMaterias.addItem(m);

        }
    }

    private void armarCabecera() {

        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Nombre");
        columnas.add("Apellido");
        columnas.add("Nota");
        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        jtDescripcionAlumnos.setModel(modelo);
    }
    
    private void llenarTabla() {

        borrarFilas();
        Materia elegida =  (Materia) jcmMaterias.getSelectedItem();

        if(elegida!=null){
        
            for(Inscripcion c:cursada.cursadaXMateria(elegida)){
            
                if(c.getMateria().equals(elegida)){
                
                    modelo.addRow(new Object[]{c.getId(),c.getAlumno().getNombre(),c.getAlumno().getApellido(),c.getNota()});
                }
            }
        }

    }
    
    private void borrarFilas() {

        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Materia> jcmMaterias;
    private javax.swing.JTable jtDescripcionAlumnos;
    // End of variables declaration//GEN-END:variables
}
